[project]
name = "MCP_Server"
version = "0.1.0"
description = "Weather MCP server"
authors = [
    { name = "Syed" }
]
requires-python = ">=3.10"
dependencies = [
    "mcp",
    "httpx"
]

[project.scripts]
mcp_server = "mcp_server.mcp_server:run"

[tool.setuptools.packages.find]
where = ["."]

