[project]
name = "weather"
version = "0.1.0"
description = "Weather MCP server"
authors = [
    { name = "Syed" }
]
requires-python = ">=3.10"
dependencies = [
    "mcp",
    "httpx"
]

[project.scripts]
weather = "weather.server:run"

[tool.setuptools.packages.find]
where = ["."]

